import type { Metadata } from "next";
import { Source_Code_Pro } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/footer";

const sourceCodePro = Source_Code_Pro({
  subsets: ["latin"],
  variable: "--font-mono",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`bg-linear-to-b from-violet-900 to-zinc-900 flex items-center justify-center bg-no-repeat flex-col scroll-smooth font-mono text-purple-50 text-balance bg-fixed gap-32 antialiased ${sourceCodePro.variable}`}
      >
        <Header
        className={`flex h-20 items-center w-full justify-center fixed top-0 px-3 z-50 text-purple-50 font-bold`}
        />
        <main className="flex flex-col items-center justify-center size-full gap-32">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
