import type { Metadata } from "next";
import { Cascadia_Code } from "next/font/google";
import "./globals.css";


const CascadiaCode = Cascadia_Code({
  variable: "--font-cascadia-code",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-linear-to-b from-violet-900 to-zinc-900 flex items-center justify-center bg-no-repeat flex-col font-sans scroll-smooth text-purple-50 text-balance bg-fixed ${CascadiaCode.variable} antialiased `}
      >
        {children}
      </body>
    </html>
  );
}
